name: gh-pages

on: 
 workflow_dispatch:
    inputs:
     branches:
      description: App name to build
      options:
       - master
      default: master
      

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn generate --datadir ./data --outfile optimism.tokenlist.json


      - name: Commit token list
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'bot(ci): generate token list'
          file_pattern: optimism.tokenlist.json

