name: gh-pages

on: 
 workflow_dispatch:
    inputs:
     branches:
      description: App name to build
      options:
       - master
      default: master
      

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i -g pnpm && pnpm install

      - name: Build
        run: pnpm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/hoppscotch-app/dist
          cname: hop.shuai.dev
